kind: ConfigMap 
apiVersion: v1 
metadata:
  name: csrx-config-map
data:
 csrx_license: |
 
 
 
 csrx_config: |
    interfaces {
     ge-0/0/0 {
        unit 0;
     }
     ge-0/0/1 {
        unit 0;
     }
    }
    security {
        policies {
            default-policy {
                permit-all;
            }
        }
        zones {
            security-zone trust {
                host-inbound-traffic {
                    system-services {
                        all;
                    }
                    protocols {
                        all;
                    }
                }
                interfaces {
                    ge-0/0/0.0;
                }
            }
            security-zone untrust {
                host-inbound-traffic {
                    system-services {
                        all;
                    }
                    protocols {
                        all;
                    }
                }
                interfaces {
                    ge-0/0/1.0;
                }
            }
        }
    } 
