
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: red 
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-1",
      "promiscMode": true,
      "ipam": {
        "type": "static",
		"addresses": [
			{
				"address": "20.0.0.10/24"
			}
		],
		"routes": [
			{ "dst": "0.0.0.0/0" },
			{ "dst": "30.0.0.0/24", "gw": "20.0.0.11" }
		]
      }
    }'

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: orange 
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-1",
      "promiscMode": true,
      "ipam": {
        "type": "static",
	    "addresses": [
			{
				"address": "20.0.0.11/24"
			}
		],
		"routes": [
			{ "dst": "0.0.0.0/0" }
		]
      }
    }'

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: green 
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-2",
      "promiscMode": true,
      "ipam": {
        "type": "static",
		"addresses": [
			{
				"address": "30.0.0.11/24"
			}
		],
		"routes": [
			{ "dst": "0.0.0.0/0" }
		]
      }
    }'

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: blue 
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-2",
      "promiscMode": true,
      "ipam": {
        "type": "static",
		"addresses": [
			{
				"address": "30.0.0.10/24"
			}
		],
		"routes": [
			{ "dst": "0.0.0.0/0" },
			{ "dst": "20.0.0.0/24", "gw": "30.0.0.11" }
		]
      }
    }'

